### ISSUE TITLE
xfstests, I/O verification tools?

### ISSUE THREAD

**Issue by sitsofe** [billziss-gh/secfs.test#1]
Hi, I'm aware that you target Windows but since you have some Linux/BSD tools in your list I'm curious as to your thoughts on [xfstests](https://git.kernel.org/pub/scm/fs/xfs/xfstests-dev.git/tree/) (some of its tests are generic despite the name). Also I'm wondering whether tools that can do verified I/O (fio/vdbench/dt) or plain stressful I/O (Microsoft's diskspd) would make your list...

(A longer list can be seen over on http://stackoverflow.com/questions/21565865/filesystem-test-suites but they are targetting Linux rather than Windows and may run afoul of critera that they should avoid being "difficult to find, not well maintained [or] quirky and buggy")

**Comment by billziss-gh** [comment]
@sitsofe I am happy to add anything that helps test file systems into this collection.

I put together this collection when developing my file system **secfs** and I only added tools that I could port to OSX (because that is actually my main development platform :) Later I added Windows tools when I became interested in running my file systems on Windows and developed WinFsp.

So feel free to send pull requests to add your favorite tools, etc. The only requirements that I have:

1. That they are open source so I can include them here.
2. That they can be used to test multiple file systems (not just a specific one).

> I'm curious as to your thoughts on xfstests

I seem to recall looking at it. I do not recall why I chose not to include it, it was either because it was too XFS specific or because I could not port it to OSX. OTOH I was able to port [fsstress](https://github.com/billziss-gh/secfs.test/tree/master/fsstress) so I added that.

> Also I'm wondering whether tools that can do verified I/O (fio/vdbench/dt) or plain stressful I/O (Microsoft's diskspd) would make your list

They absolutely would (if they are open source and generic enough to be used on many file systems as stated above).

**Comment by sitsofe** [comment]
@billziss-gh
> So feel free to send pull requests to add your favorite tools, etc. 

OK let's see if I can walk the walk. Might take some time... 

> I seem to recall looking at it. I do not recall why I chose not to include it, it was either because it was too XFS specific or because I could not port it to OSX.

I'd say that at now there are (allegedly) generic tests: https://git.kernel.org/pub/scm/fs/xfs/xfstests-dev.git/tree/tests/generic but that notwithstanding the lack of an OSX version would explain why it wasn't useful to you :-) 

> > Also I'm wondering whether tools that can do verified I/O (fio/vdbench/dt) or plain stressful I/O (Microsoft's diskspd) would make your list
>
> They absolutely would (if they are open source and generic enough to be used on many file systems as stated above).

Certainly [fio](https://github.com/axboe/fio/) is portable (I've personally run it on OSX, Windows and Linux), has a GPLv2 license and works under all those OSes default filesystems. vdbench is bit trickier because while the source is available the license appears to be "Oracle Technology Network" so I doubt its opensource. diskspd is under the MIT license but as you might expect from Microsoft its Windows only (even though it technically supports multiple FSes on Windows).

OK let's close this issue for now - thanks for the rapid reply and explanations!

**Comment by billziss-gh** [comment]
> OK let's see if I can walk the walk. Might take some time...

Thank you! Would love to get more tools for testing :)

> Certainly fio is portable (I've personally run it on OSX, Windows and Linux), has a GPLv2 license and works under all those OSes default filesystems.

This actually looks very interesting. I might try it myself to see if I can make it work with my file systems.
